boost_heating:
  name: Boost Heating
  description: >
    Boost the temperature in the selected rooms/areas.
  target:
    entity:
      integration: wiser
      domain: climate
  fields:
    time_period:
      name: Time period
      description: Set the time period for the boost in minutes.
      example: 60
      default: 60
      required: true
      selector:
        number:
          min: 1
          max: 9999
          step: 1
          mode: box
    temperature_delta:
      name: Temperature Increase
      description: Set the increase in temperature for the boost period.
      example: 3.0
      default: 3.0
      required: false
      selector:
        number:
          min: 0.5
          max: 5
          step: 0.5
          unit_of_measurement: C
    temperature:
      name: Temperature
      description: Set the room target temperature for the boost period.
      example: 21.0
      default: 21.0
      required: false
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: C

boost_hotwater:
  name: Boost Hot Water
  description: >
    Boost the hot water for time specified.
  target:
    entity:
      integration: wiser
      domain: select
  fields:
    time_period:
      name: Time period
      description: Set the time period for the boost in minutes.
      example: 60
      default: 60
      required: true
      selector:
        number:
          min: 1
          max: 1440
          step: 1
          mode: box

get_schedule:
  name: Save Schedule to File
  description: >
    Read the schedule from a room or device and write to an output file in yaml
  fields:
    entity_id:
      name: Entity
      description: A wiser entity
      required: true
      selector:
        entity:
          integration: wiser
          domain: 
          - climate
          - select
    filename:
      name: Filename
      description: >
        The filename to write out the yaml. See README.MD if running within a
        docker container.
      required: false
      example: "config/schedules/{{ entity_id.name }}.yaml"
      selector:
        text:

set_schedule:
  name: Set Schedule From File
  description: Read in the yaml schedule file and set the schedule
  fields:
    entity_id:
      name: Entity
      description: A wiser entity
      required: true
      selector:
        entity:
          integration: wiser
          domain: 
          - climate
          - select
    filename:
      name: Filename
      description: The filename to read the yaml schedule from.
      required: true
      example: schedules/schedule1.yaml
      selector:
        text:

copy_schedule:
  name: Copy Schedule
  description: Copy the schedule from one to another in the same type
  fields:
    entity_id:
      name: Entity
      description: A wiser entity
      required: true
      selector:
        entity:
          integration: wiser
          domain: 
          - climate
          - select
    to_entity_id:
      name: To Entity
      description: Enter the entity_id for the room to copy the schedule to.
      required: true
      example: climate.wiser_kitchen
      selector:
        entity:
          integration: wiser
          domain: 
          - climate
          - select

assign_schedule:
  name: Assign Schedule
  description: Assign the schedule to other rooms or devices in the same type
  fields:
    entity_id:
      name: Entity
      description: A wiser entity
      required: false
      selector:
        entity:
          integration: wiser
          domain: 
          - climate
          - select
    schedule_id:
      name: Schedule Id
      description: A wiser schedule id
      required: false
      selector:
        number:
          mode: box
    to_entity_id:
      name: To Entity
      description: Enter the entity_id for the room or device to assign the same schedule to.
      required: true
      example: climate.wiser_kitchen
      selector:
        entity:
          integration: wiser
          domain: 
          - climate
          - select

set_device_mode:
  name: "Set Device Mode"
  description: Sets the device mode to auto or manual
  fields:
    entity_id:
      name: Entity
      description: A wiser mode entity
      required: true
      selector:
        entity:
          integration: wiser
          domain: select
    mode:
      name: "Mode"
      description: Enter the mode which can be manual or auto.
      required: true
      example: auto
      selector:
        select:
          options:
            - "Auto"
            - "Manual"

remove_orphaned_entries:
  name: Remove Orphaned Devices
  description: Delete devices that no longer exist on Wiser
  fields:
    wiser_hub_id:
      name: Wiser Hub Name
      description: >-
        The name of the wiser hub to remove orhpaned devices from.  
        This can be found from the integration name.
      example: WiserHeatxxxxxx
      required: true
      selector:
        text:

output_hub_json:
  name: Output Hub Json Data To File
  description: Write anonymised hub json data to file for debug purposes
  fields:
    wiser_hub_id:
      name: Wiser Hub Name
      description: >-
        The name of the wiser hub to get json data from.  
        This can be found from the integration name.
      example: WiserHeatxxxxxx
      required: true
      selector:
        text:
